# Generated by Django 4.1.4 on 2022-12-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='imageURL',
            field=models.ImageField(blank=True, null=True, upload_to='Profile-photos/'),
        ),
    ]
