# Generated by Django 4.1.4 on 2022-12-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='imageURL',
            field=models.URLField(max_length=300),
        ),
    ]
