# Generated by Django 4.1.4 on 2022-12-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
