# Generated by Django 4.1.4 on 2022-12-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
