# Generated by Django 4.1.4 on 2022-12-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
    ]
