# Generated by Django 4.1.4 on 2022-12-16 20:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0004_car_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('imageURL', models.URLField(max_length=300)),
                ('publication_date', models.DateField(auto_now=True)),
                ('tagged_cars', models.ManyToManyField(blank=True, to='common.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
